#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

# paths for source and target
readonly TARGET_HOST=tflint@cam4.local
readonly TARGET_PATH=/home/tflint/dcampi
readonly TARGET_ARCH=aarch64-unknown-linux-gnu
readonly SOURCE_PATH=../target/${TARGET_ARCH}/release/dcampi

# also copy the html files
readonly SOURCE_HTML=./src/*
readonly TARGET_HTML=${TARGET_PATH}/src
readonly SOURCE_ROCKET=./Rocket.toml

# set up environment variables for cross-compilation with sysroot
export PKG_CONFIG_SYSROOT_DIR=/home/tflint/Documents/pi0root
export PKG_CONFIG_ALLOW_CROSS=1
export PKG_CONFIG_PATH=/home/tflint/Documents/pi0root/usr/lib/aarch64-linux-gnu/pkgconfig

cargo build --release --target=${TARGET_ARCH}
rsync ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}
rsync ${SOURCE_HTML} ${TARGET_HOST}:${TARGET_HTML}
rsync ${SOURCE_ROCKET} ${TARGET_HOST}:${TARGET_PATH}
ssh -t ${TARGET_HOST} "
    cd ${TARGET_PATH}
    ./dcampi
    "

